deploy:
  needs: build_push
  if: github.ref == 'refs/heads/main'
  runs-on: [self-hosted, linux]   # сюда можно добавить свой label, например [self-hosted, linux, dvorik]
  steps:
    - name: Docker login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Deploy containers
      run: |
        cd /opt/dvorik
        export DOCKER_IMAGE=msnq/dvorik:latest
        docker compose pull
        docker compose up -d
        docker image prune -f
